using UnityEngine;
using UnityEngine.SceneManagement;

public class MainMenuManager : MonoBehaviour {
    private bool isSelectMenu = false;
    private bool isConfirm = false;

    private MainMenuController mainMenuController;
    private ConfirmManager confirmManager;
    private MainManager mainManager;

    private void Awake() {
        mainMenuController = FindObjectOfType<MainMenuController>();
        mainManager = FindObjectOfType<MainManager>();
        confirmManager = FindObjectOfType<ConfirmManager>();
    }

    private void Start() {
        mainMenuController.gameObject.SetActive(false);
    }

    private void Update() {
        if (!isConfirm && isSelectMenu && Input.GetButtonDown("Cancel")) {
            CloseMenu();
            return;
        }

        //Ю Т OPEN
        if (
            (!isSelectMenu && Input.GetButtonDown("menu"))
                || (!isSelectMenu && Input.GetButtonDown("Select"))
                || (!isSelectMenu && Input.GetMouseButtonDown(0))
            ) {
            ShowMenu(); 
            return;
        }

        //Ю Т 첇
        if (!isConfirm && isSelectMenu && Input.GetButtonDown("Horizontal")) {
            float horizontalInput = Input.GetAxis("Horizontal");
            if (horizontalInput > 0) {
                mainMenuController.NextButtonClick();
            }
            else {
                mainMenuController.PrevButtonClick();
            }
            return;
        }

        //컈 칙 CLOSE
        if (isConfirm && Input.GetButtonDown("Cancel")) {
            CloseConfirm();
            return;
        }

        //컈 칙 쨤콲 뫥 Т 첇 / 컈칙 얳쐑
        if ((isConfirm && Input.GetButtonDown("Select")) || (isConfirm && Input.GetButtonDown("menu"))) {
            if (confirmManager.GetIsHoverYes()) {
                GoToMenu();
            }
            else {
                CloseConfirm(); 
                return;
            }
        }

        //컈 칙 OPEN OR MENU 첇
        if ((!isConfirm && isSelectMenu && Input.GetButtonDown("Select")) || (!isConfirm && isSelectMenu && Input.GetButtonDown("menu"))) {
            switch (mainMenuController.GetSelectMenu()) {
                case MenuType.PLAY_LOCAL:
                    PlayerPrefs.SetInt("localGame", 1);
                    SceneManager.LoadScene("Game_List");
                    break;
                case MenuType.PLAY_ONLINE:
                    ShowConfirm();
                    confirmManager.ConfirmMainTextChage(mainMenuController.GetSelectMenu());
                    break;
                case MenuType.OPTION:
                    mainManager.OpenDLCDialog();
                    break;
                case MenuType.EXIT:
                    ShowConfirm();
                    confirmManager.ConfirmMainTextChage(mainMenuController.GetSelectMenu());
                    break;
            }
            return;
        }
    }

    #region Ю Т
    private void ShowMenu() {
        mainMenuController.gameObject.SetActive(true);
        isSelectMenu = true;
    }

    public void CloseMenu() {
        mainMenuController.gameObject.SetActive(false);
        isSelectMenu = false;
    }
    #endregion

    #region 컈칙
    public void ShowConfirm() {
        confirmManager.gameObject.SetActive(true);
        isConfirm = true;
    }

    public void CloseConfirm() {
        confirmManager.gameObject.SetActive(false);
        isConfirm = false;
    }
    #endregion

    public void GoToMenu() {
        switch (mainMenuController.GetSelectMenu()) {
            case MenuType.PLAY_LOCAL:
                PlayerPrefs.SetInt("localGame", 1);
                SceneManager.LoadScene("Game_List");
                break;
            case MenuType.PLAY_ONLINE:
                mainManager.OpenOnlineCanvas();
                break;
            case MenuType.OPTION:
                mainManager.OpenDLCDialog();
                break;
            case MenuType.EXIT:
                break;
        }
    }
}
